
import controller.clientesController;
import dao.generalDao;
import daoImpl.generalDaoImpl;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelos.usuario;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class usuarios extends javax.swing.JFrame {

    private Object con;
    private Object e;

    /**
     * Creates new form usuarios
     */
    public usuarios() {
        initComponents();
        this.setTitle("LABORATORIO MEDICO LA BENDICIÓN ");
        this.setLocation(400, 240);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        checkbox1 = new java.awt.Checkbox();
        lbl_fondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_nit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        txt_contraseña = new javax.swing.JPasswordField();
        txt_telefono = new javax.swing.JTextField();
        txt_cui = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        cmb_tipo_usuario = new javax.swing.JComboBox<>();
        btn_crear_usuario = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        lbl_imagen_usuario = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();
        botn_salir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jdc_calendario = new com.toedter.calendar.JDateChooser();

        jLabel4.setText("jLabel4");

        jPasswordField1.setText("jPasswordField1");

        checkbox1.setLabel("checkbox1");

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/292ddcf1fdbcff99169b93d6507b59bf.jpg"))); // NOI18N
        lbl_fondo.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Nit");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 70, 20));

        txt_nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nitActionPerformed(evt);
            }
        });
        txt_nit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nitKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 350, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Completo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Correo Electrónico");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Contraseña");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Teléfono ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 80, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Dirección ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Cui");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Fecha Nacimiento ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, 20));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Tipo Usuario ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 350, 30));

        txt_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correoActionPerformed(evt);
            }
        });
        txt_correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_correoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 350, 30));

        txt_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 210, 30));

        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });
        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 350, 30));

        txt_cui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cuiActionPerformed(evt);
            }
        });
        txt_cui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cuiKeyTyped(evt);
            }
        });
        getContentPane().add(txt_cui, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 350, 30));

        txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 350, 30));

        cmb_tipo_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario Interno", "Usuario Externo", " " }));
        cmb_tipo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipo_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_tipo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        btn_crear_usuario.setBackground(new java.awt.Color(0, 102, 102));
        btn_crear_usuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_crear_usuario.setText("CREAR");
        btn_crear_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crear_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_crear_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 110, 40));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setText("Registro Usuarios");
        jLabel11.setMaximumSize(new java.awt.Dimension(299, 30));
        jLabel11.setRequestFocusEnabled(false);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 270, 40));

        txt_id.setEditable(false);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 50, 30));

        jLabel12.setText("id");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 30, -1));

        btn_salir.setBackground(new java.awt.Color(0, 153, 204));
        btn_salir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_salir.setText("REGRESAR");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 110, 40));

        lbl_imagen_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono.png"))); // NOI18N
        lbl_imagen_usuario.setText("jLabel13");
        getContentPane().add(lbl_imagen_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 330, 370));

        jCheckBox1.setText("Mostrar");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 80, 30));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Edad:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        txt_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edadActionPerformed(evt);
            }
        });
        txt_edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_edadKeyTyped(evt);
            }
        });
        getContentPane().add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 120, 30));

        botn_salir.setBackground(new java.awt.Color(255, 51, 51));
        botn_salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botn_salir.setText("SALIR");
        botn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(botn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 100, 40));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 560));
        getContentPane().add(jdc_calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 300, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nitActionPerformed

    private void txt_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correoActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
        
        ///usuario puede ingresar numeros y letras///
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void btn_crear_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crear_usuarioActionPerformed
        /*aqui*//////
        String cadena2, cadena3, cadena4, cadena5, cadena6, cadena7, cadena8, cadena9, cadena10, cadena11;
        cadena2 = txt_nit.getText();
        cadena3 = txt_nombre.getText();
        cadena4 = txt_correo.getText();
        cadena5 = txt_contraseña.getText();
        cadena6 = txt_telefono.getText();
        cadena7 = txt_direccion.getText();
        cadena8 = txt_cui.getText();
        cadena9 = jdc_calendario.getDateFormatString();
        cadena10 = cmb_tipo_usuario.getSelectedItem().toString();
        cadena11 = txt_edad.getText();

        if (txt_nit.getText().equals("") || (txt_nombre.getText().equals("")) || (txt_correo.getText().equals("")) || (txt_contraseña.getText().equals("")) /// VALIDACION PARA QUE TODOS LOS CAMPOS ESTEN LLENOS
                || (txt_telefono.getText().equals("")) || (txt_direccion.getText().equals("")) || (txt_cui.getText().equals(""))
                || (cmb_tipo_usuario.getSelectedItem().equals("") || (txt_edad.getText().equals("")))) {

            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            txt_nombre.requestFocus();
        } else {

            boolean evaluar;

            usuario userInsert = new usuario();
            userInsert.setTxt_nit(cadena2);
            userInsert.setTxt_nombre(cadena3);
            userInsert.setTxt_correo(cadena4);
            userInsert.setTxt_contrasena(cadena6);
            userInsert.setTxt_direccion(cadena7);
            userInsert.setTxt_edad(cadena11);
            userInsert.setTxt_cui(cadena8);
            userInsert.setJdc_calendario(cadena9);
            userInsert.setCmb_tipo_usuario(cadena10);

            generalDao dao = new generalDaoImpl();
            evaluar = dao.registrar(userInsert);

            if (evaluar) {
                javax.swing.JOptionPane.showMessageDialog(this, "Registro exitoso! \n", "AVISO!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Registro no exitoso! \n", "AVISO!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

        }
        this.txt_nit.setText("");
        this.txt_nombre.setText("");
        this.txt_correo.setText("");
        this.txt_contraseña.setText("");
        this.txt_telefono.setText("");
        this.txt_direccion.setText("");
        this.txt_cui.setText("");
        this.jdc_calendario.setDateFormatString("");
        this.cmb_tipo_usuario.setSelectedItem("");
        this.txt_edad.setText("");

    }//GEN-LAST:event_btn_crear_usuarioActionPerformed

    private void txt_nitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nitKeyTyped

    }//GEN-LAST:event_txt_nitKeyTyped

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }   ///validando que los caracteres ingresados sean tipo numericos en este campo/// 
    }//GEN-LAST:event_txt_telefonoKeyTyped

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped

    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void cmb_tipo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipo_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipo_usuarioActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        Login_principal log = new Login_principal();
        log.setVisible(true);       //// codigo para regresar a la pantalla login////
    }//GEN-LAST:event_btn_salirActionPerformed

    private void txt_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraseñaActionPerformed

    private void txt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionActionPerformed

    private void txt_cuiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cuiKeyTyped
        int numerocarateres = 13;     /// Codigo que permite unicamente el ingreso de 13 caracteres a dicho campo///

        if (txt_cui.getText().length() >= numerocarateres) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo 13 Caractere");
        }
    }//GEN-LAST:event_txt_cuiKeyTyped

    private void txt_cuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cuiActionPerformed

    }//GEN-LAST:event_txt_cuiActionPerformed

    private void txt_correoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_correoKeyTyped

    }//GEN-LAST:event_txt_correoKeyTyped

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) //// codigo para validar contraseña////
        {
            txt_contraseña.setEchoChar((char) 0);
        } else {
            txt_contraseña.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void txt_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edadActionPerformed

    }//GEN-LAST:event_txt_edadActionPerformed

    private void txt_edadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_edadKeyTyped
        /* char c = evt.getKeyChar();
       if(c<'0' || c>'9' ) evt.consume(); */  ///validando que los caracteres ingresados sean tipo numericos en este campo/// 
        int numero = 2;     /// Codigo que permite unicamente el ingreso de 13 caracteres a dicho campo///

        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }

        if (txt_edad.getText().length() >= numero) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo 2 caracteres");
        }


    }//GEN-LAST:event_txt_edadKeyTyped

    private void botn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botn_salirActionPerformed
         System.exit(WIDTH);    ///cerrar el jframe    // TODO add your handling code here:
    }//GEN-LAST:event_botn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botn_salir;
    private javax.swing.JButton btn_crear_usuario;
    private javax.swing.JButton btn_salir;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JComboBox<String> cmb_tipo_usuario;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private com.toedter.calendar.JDateChooser jdc_calendario;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_imagen_usuario;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_cui;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nit;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables

    private static class Toast {

        public Toast() {
        }
    }
}
